version: '3.9'

services:
  voice_service:
    container_name: voice_service
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    env_file: .env
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    networks:
      - service_network

networks:
  service_network:
