// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: voice_service.proto

package medical_voice_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoiceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *VoiceData) Reset() {
	*x = VoiceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voice_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoiceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceData) ProtoMessage() {}

func (x *VoiceData) ProtoReflect() protoreflect.Message {
	mi := &file_voice_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceData.ProtoReflect.Descriptor instead.
func (*VoiceData) Descriptor() ([]byte, []int) {
	return file_voice_service_proto_rawDescGZIP(), []int{0}
}

func (x *VoiceData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type VoiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *VoiceResponse) Reset() {
	*x = VoiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voice_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceResponse) ProtoMessage() {}

func (x *VoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceResponse.ProtoReflect.Descriptor instead.
func (*VoiceResponse) Descriptor() ([]byte, []int) {
	return file_voice_service_proto_rawDescGZIP(), []int{1}
}

func (x *VoiceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_voice_service_proto protoreflect.FileDescriptor

var file_voice_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x22, 0x1f, 0x0a, 0x09,
	0x56, 0x6f, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x23, 0x0a,
	0x0d, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x32, 0x4f, 0x0a, 0x0c, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3f, 0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x56, 0x6f,
	0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e,
	0x56, 0x6f, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x14, 0x2e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x2e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x42, 0x12, 0x5a, 0x10, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_voice_service_proto_rawDescOnce sync.Once
	file_voice_service_proto_rawDescData = file_voice_service_proto_rawDesc
)

func file_voice_service_proto_rawDescGZIP() []byte {
	file_voice_service_proto_rawDescOnce.Do(func() {
		file_voice_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_voice_service_proto_rawDescData)
	})
	return file_voice_service_proto_rawDescData
}

var file_voice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_voice_service_proto_goTypes = []interface{}{
	(*VoiceData)(nil),     // 0: voice.VoiceData
	(*VoiceResponse)(nil), // 1: voice.VoiceResponse
}
var file_voice_service_proto_depIdxs = []int32{
	0, // 0: voice.VoiceService.transferVoiceData:input_type -> voice.VoiceData
	1, // 1: voice.VoiceService.transferVoiceData:output_type -> voice.VoiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_voice_service_proto_init() }
func file_voice_service_proto_init() {
	if File_voice_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_voice_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoiceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voice_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_voice_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voice_service_proto_goTypes,
		DependencyIndexes: file_voice_service_proto_depIdxs,
		MessageInfos:      file_voice_service_proto_msgTypes,
	}.Build()
	File_voice_service_proto = out.File
	file_voice_service_proto_rawDesc = nil
	file_voice_service_proto_goTypes = nil
	file_voice_service_proto_depIdxs = nil
}
